config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :appointments

root to: "appointments#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  # validates :customer_name, presence: true,:uniq=>true

  belongs_to :salon

  validates :customer_age,:customer_name,:appointment_date,:time_slot, presence: true
  validates_uniqueness_of :customer_name
  validates :customer_age, :numericality => { :greater_than_or_equal_to => 0 }



  validate :check_availability?

  def check_availability?
    unless self.appointment_date.nil?
    appointment = Appointment.where(:appointment_date=>self.appointment_date,:time_slot=>self.time_slot)
    if appointment.present? || self.appointment_date < Date.today
    errors.add(:appointment_date, "Slot Not Available")
    end
    end
  end

end

app/models/salon.rb
class Salon < ApplicationRecord

  has_many :appointments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController


# List Appointments
  def index
   @appointments = Appointment.where("appointment_date >= ?",Date.today).order('appointment_date asc')
  end

  def new
    @new_appointment = Appointment.new
  end

  # Booking Appointment
  def create
    @new_appointment = Appointment.new(appointment_params)
     respond_to do |format|
      if @new_appointment.save
        format.html { redirect_to appointments_path, notice: 'Your Appointment was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end

  def show


  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @appointment = Appointment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def appointment_params
    params.require(:appointment).permit(:salon_id,:customer_name, :customer_age,:appointment_date,:time_slot)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: "panel panel-danger") do
        concat(content_tag(:div, class: "panel-heading") do
          concat(content_tag(:h4, class: "panel-title") do
            concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: "panel-body",:style=>'color:red') do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end

  def get_salon_id
    unless Salon.first.present?
         Salon.create(:name=> 'Sweet Pixie Salon',:contact_number=>'1111111111',:description=>'We are popular salon in india')
    end
    return Salon.first.id

  end

  def update_active_menu(url)

    if url == ('/' || '/appointments')
      return 'active'
    elsif url == '/appointments/new'
      return 'active'
    else

      return ''
    end

  end

end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">List of Appointments</div>
  <div class="panel-body">

  </div>
<table id="appointments" class="table table-striped table-bordered" cellspacing="0" width="100%">
<thead>
<tr>
  <th>Customer Name</th>
  <th>Customer Age</th>
  <th>Appointment Date</th>
  <th>Time Slot(Hours)</th>

</tr>
</thead>
<tfoot>
<tr>
  <th>Customer Name</th>
  <th>Customer Age</th>
  <th>Appointment Date</th>
  <th>Time Slot(Hours)</th>
</tr>
</tfoot>
<tbody>
<% @appointments.each do |each_app| %>
<tr>
  <td><%= each_app.customer_name %></td>
  <td><%= each_app.customer_age %></td>
  <td><%= each_app.appointment_date %></td>
  <td><%= each_app.time_slot %></td>

</tr>
<% end %>
</tbody>
</table>

</div>
<script>

    $(document).ready(function() {
        $('#appointments').DataTable();
    } );
</script>

app/views/appointments/new.html.erb
<%= stylesheet_link_tag    'application', media: 'all' %>
<div class="album text-muted">
  <div class="container">
    <div class="row main">
      <div class="main-login main-center">
        <h1>Book Appointment</h1>
        <%= form_for @new_appointment, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
            <%= errors_for(@new_appointment) %>

            <div class="form-group">
              <label for="name" class="cols-sm-2 control-label">Your Name</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
                   <%= f.text_field :customer_name,:class=>"form-control",:placeholder=>"Enter your Name",:required=>true %>
                  <%= f.hidden_field :salon_id, :value => get_salon_id%>
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="email" class="cols-sm-2 control-label">Your Age</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
                    <%= f.text_field :customer_age,:class=>"form-control",:placeholder=>"Enter your Age",:required=>true %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="confirm" class="cols-sm-2 control-label">Appointment Date</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" aria-hidden="true"></i></span>
                  <%= f.date_field :appointment_date, :class=> "form-control",:required=>true %>

                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="password" class="cols-sm-2 control-label">Time Slot(Hours)</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-time" aria-hidden="true"></i></span>
                  <%= f.select(:time_slot, ['10', '11','12','13','15','16','17','18','19'], {include_blank: "--- Select Slot ---"}, { :class => 'form-control',:required=>true }) %>
                </div>
              </div>
            </div>
            <div class="form-group ">
              <%= f.submit "Book Appointment",:class=>"btn btn-primary btn-lg btn-block login-button" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Sweet Pixie Salon</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="<%= (request.path == '/' || request.path == '/appointments') ? 'active' : '' %>"><%= link_to "Home", appointments_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= (request.path == '/appointments/new') ? 'active' : '' %>">
          <%= link_to new_appointment_path do %>
              Book Appointment
              <span class="glyphicon glyphicon-calendar"></span>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <%#= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>

  <style>
      /* Remove the navbar's default rounded borders and increase the bottom margin */
      .navbar {
          margin-bottom: 50px;
          border-radius: 0;
      }

      /* Remove the jumbotron's default bottom margin */
      .jumbotron {
          margin-bottom: 0;
      }

      /* Add a gray background color and some padding to the footer */
      footer {
          background-color: #f2f2f2;
          padding: 25px;
      }
  </style>
</head>
<body>

<%= render :partial=>'layouts/header' %>

<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%= yield %>
</div><br>

<footer class="container-fluid text-center">

</footer>

</body>
</html>